### ISSUE TITLE
Arduino compatibility

### ISSUE THREAD

**Issue by fpapadopou** [sparkfun/SparkFun_MAX17043_Particle_Library#4]
Hey there! This is Fotis from [codebender](https://codebender.cc). Is this library Arduino-compatible? It looks like the code of the library is compatible, but the example is only supported in Particle Cloud IDE. Could you please create an Arduino version of the example.We need the example in order to host the library in codebender. Thanks!!

**Comment by lmorris99** [comment]
same here: I use the Arduino IDE "Add library from .zip file", and get "Specified folder/zip file does not contain a valid library".

**Comment by bboyho** [comment]
Hi,

I noticed this issue was filed when browsing our issues. It would need to be ported to work with Arduino. It looks like this IC is used on the [SparkFun LiPo Fuel Gauge](https://www.sparkfun.com/products/10617). We do not have an official library but one of our tech support reps found this library and example code. It seems to work ok.

There is also another [Arduino library](https://github.com/porrey/max1704x) that you can find in the Arduino library manager if you search for **MAX1704X**. This is written by Daniel Porrey. 

Another alternative is to write the functions to read the MAX17043 in the sketch like [example 3 in the Wireless Joystick tutorial](https://learn.sparkfun.com/tutorials/wireless-joystick-hookup-guide#arduino-examples).
